version: "3"

services:
  postgres:
    image: "postgres:11"

  pylabber:
    build: .
    command: >
      sh -c "python manage.py makemigrations && \
             python manage.py migrate && \
             echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@labbing.com', 'admin')\" | python manage.py shell && \
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      FSLOUTPUTTYPE: "NIFTI_GZ"
    depends_on:
      - postgres
